# WhatATheme
markdown: kramdown

url: https://nathaniel2go.github.io
baseurl: ""

# Title of the Site
title: Nathaniel Go
# Description of the Site
description:  Nathaniel Go's Personal Site.
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Photography, Portfolio, Graphics, CAD, Engineering, SYDE, Systems Design Engineering, UW, Uwaterloo, University of Waterloo
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://i.imgur.com/pw7cLms.jpeg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: n2go@uwaterloo.ca
facebook_username: 
twitter_username: 
instagram_username: NetTheNut
linkedin_username: NathanielDeanToGo
github_username:  nateDgreat48
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: 

collections:
  portfolios:
    output: true
    permalink: /portfolios/:title/

# Name of the Author
author-name: Nathaniel Go
# URL for the Image of the Author
author-image: https://i.imgur.com/kKBe5ya.jpeg
# 60 Words About the Author
author-about: I am an engineering student at the University of Waterloo, specializing in Systems Design Engineering (BASc). I am exploring options in photography, graphics, and CAD. I invite you to explore my page as it contains projects, products, and portfolios.  
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://linktr.ee/NathanielGo

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
